# version: '3.8'

# services:
#   mysql:
#     image: mysql
#     container_name: backend-expressjs
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: myuser
#       MYSQL_PASSWORD: mypassword
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data:
#     driver: local

version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-express
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/var/lib/mysql

volumes:
  mongodb-data:
    driver: local
